name: Build Windows Forms App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild Vehicle-Tracking-System.sln /p:Configuration=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: |
          **/bin/Release/
